/* Copyright (c) Stichting Mathematisch Centrum, Amsterdam, 1987. */

/* If you change this file, don't forget ../bhdrs/b0lan.h and bint2/i2dis.c */

#define R_HOW_TO	"HOW TO "
#define R_PASS		"PASS"
#define R_PUT		"PUT "
#define R_IN_put	" IN "
#define R_INSERT	"INSERT "
#define R_IN_insert	" IN "
#define R_REMOVE	"REMOVE "
#define R_FROM_remove	" FROM "
#define R_SET_RANDOM	"SET RANDOM "
#define R_DELETE	"DELETE "
#define R_CHECK 	"CHECK "
#define R_SHARE 	"SHARE "
#define R_WRITE 	"WRITE "
#define R_READ		"READ "
#define R_EG		" EG "
#define R_RAW		" RAW"
#define R_IF		"IF "
#define R_WHILE 	"WHILE "
#define R_FOR		"FOR "
#define R_IN_for	" IN "
#define R_SELECT	"SELECT: "
#define R_ELSE		"ELSE"
#define R_QUIT		"QUIT"
#define R_RETURN	"RETURN "
#define R_REPORT	"REPORT "
#define R_SUCCEED	"SUCCEED"
#define R_FAIL		"FAIL"
#define R_AND		"AND "
#define R_OR		"OR "
#define R_NOT		"NOT "
#define R_SOME		"SOME "
#define R_EACH		"EACH "
#define R_NO		"NO "
#define R_IN_quant	" IN "
#define R_PARSING	" PARSING "
#define R_HAS		" HAS "

#ifdef GFX
#define R_SPACE 	"SPACE "
#define R_TO_space	" TO "
#define R_LINE		"LINE "
#define R_TO_line	" TO "
#define R_CLEAR 	"CLEAR"
#endif
